server:
  port: 8080

spring:
  application:
    name: fizzbuzz-ws
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:fizzbuzz;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  custom:
    titleApp: FizzBuzz
    versionApp: 0.0.1-SNAPSHOT

